### ISSUE TITLE
RoutingAPI AWS cdk 배포

### ISSUE THREAD

**Issue by dehypnosis** [encrypt-X/routing-api#1]
### _**Description**_
문제상황: Miro Finanace Swap 기능 구현 중 quote api의 validation check가 정상적으로 이뤄지지 않음
```
endpoint: https://0g9bougeie.execute-api.us-east-1.amazonaws.com/prod/qoute
response: ["detail":" "tokenInChainId\" must be [1261120]" "errorCode": "VALIDATION ERROR"}
```

### _**To-Do**_
- [ ] 해당 api 로직 수정
- [ ] 배포

**Comment by ouoabcde** [comment]
# 파악한 상황

- routing-api 코드에 파라미터에서 요청한 chainId 713715 이 존재하지 않음
713715: sei-dev 체인 아이디
response 에러를 보면 1261120 (zkatana), 이 체인 아이디로 요청해야 한다고 하는데, 코드의 체인 아이디 리스트의 마지막이 이 체인 아이디인 것으로 보아, 리스트의 마지막까지 매칭되는 아이디가 없어서, 마지막에 등장한 아이디로 요청해야 한다고 뜨는 에러로 예상됨
